2024-06-09 09:30:03,240 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:67]
2024-06-09 09:33:33,303 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:67]
2024-06-09 09:34:06,571 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:67]
2024-06-09 09:35:58,280 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:67]
2024-06-09 09:37:44,165 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:67]
2024-06-09 09:38:10,766 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:67]
2024-06-09 09:39:03,998 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:67]
2024-06-09 09:39:32,468 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:67]
2024-06-09 09:44:04,347 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:67]
2024-06-09 09:45:08,842 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:67]
2024-06-09 09:45:11,148 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:67]
2024-06-09 09:49:55,851 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:67]
2024-06-09 09:57:53,079 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:67]
2024-06-09 09:57:56,504 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:67]
2024-06-09 09:59:30,925 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:67]
2024-06-09 09:59:32,525 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:67]
2024-06-09 10:00:40,057 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:67]
2024-06-09 10:04:23,493 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:67]
2024-06-09 10:05:07,651 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:67]
2024-06-09 10:05:10,133 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:67]
2024-06-09 10:05:27,611 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:67]
2024-06-09 10:07:52,652 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:67]
2024-06-09 10:08:05,686 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:67]
2024-06-09 10:16:01,427 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:67]
2024-06-09 10:24:52,958 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:72]
2024-06-09 10:25:07,784 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:72]
2024-06-09 10:28:26,710 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:72]
2024-06-09 10:28:39,732 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:72]
2024-06-09 10:28:50,094 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:72]
2024-06-09 10:28:57,887 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:72]
2024-06-09 10:28:59,976 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:72]
2024-06-09 10:29:18,269 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:72]
2024-06-09 10:30:23,215 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:72]
2024-06-09 10:30:25,208 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:72]
2024-06-09 10:30:39,263 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:72]
2024-06-09 10:33:42,671 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:72]
2024-06-09 10:33:47,024 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:72]
2024-06-09 10:46:19,232 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:75]
2024-06-09 10:46:36,588 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:75]
2024-06-09 10:46:45,402 ERROR: Exception on /auth/login [GET] [in /home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/alucard/python/kfu/minkin2024/app/auth/routes.py", line 16, in login
    if current_user.is_authenticated:
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/werkzeug/local.py", line 515, in _get_current_object
    return get_name(local())
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask_login/utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask_login/utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask_login/login_manager.py", line 347, in _load_user
    raise Exception(
Exception: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info.
2024-06-09 10:46:51,671 ERROR: Exception on /auth/login [GET] [in /home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/alucard/python/kfu/minkin2024/app/auth/routes.py", line 16, in login
    if current_user.is_authenticated:
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/werkzeug/local.py", line 515, in _get_current_object
    return get_name(local())
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask_login/utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask_login/utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask_login/login_manager.py", line 347, in _load_user
    raise Exception(
Exception: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info.
2024-06-09 10:47:28,022 ERROR: Exception on /auth/login [GET] [in /home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/alucard/python/kfu/minkin2024/app/auth/routes.py", line 16, in login
    if current_user.is_authenticated:
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/werkzeug/local.py", line 515, in _get_current_object
    return get_name(local())
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask_login/utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask_login/utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask_login/login_manager.py", line 347, in _load_user
    raise Exception(
Exception: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info.
