2024-06-09 11:33:35,263 ERROR: Exception on /auth/reset_password_request [POST] [in /home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/alucard/python/kfu/minkin2024/app/auth/routes.py", line 64, in reset_password_request
    send_password_reset_email(user)
  File "/home/alucard/python/kfu/minkin2024/app/auth/email.py", line 7, in send_password_reset_email
    token = user.get_reset_password_token()
AttributeError: 'User' object has no attribute 'get_reset_password_token'
2024-06-09 11:36:17,443 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:78]
2024-06-09 11:36:31,240 ERROR: Exception on /auth/reset_password_request [POST] [in /home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/alucard/python/kfu/minkin2024/app/auth/routes.py", line 64, in reset_password_request
    send_password_reset_email(user)
  File "/home/alucard/python/kfu/minkin2024/app/auth/email.py", line 7, in send_password_reset_email
    token = user.get_reset_password_token()
  File "/home/alucard/python/kfu/minkin2024/app/models.py", line 50, in get_reset_password_token
    {'reset_password': self.id, 'exp': time() + expires_in},
AttributeError: 'User' object has no attribute 'id'
2024-06-09 11:37:04,210 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:78]
2024-06-09 11:37:08,804 ERROR: Exception on /auth/reset_password_request [POST] [in /home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/alucard/python/kfu/minkin2024/app/auth/routes.py", line 64, in reset_password_request
    send_password_reset_email(user)
  File "/home/alucard/python/kfu/minkin2024/app/auth/email.py", line 11, in send_password_reset_email
    text_body=render_template('email/reset_password.txt',
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/templating.py", line 151, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: email/reset_password.txt
2024-06-09 11:38:49,618 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:78]
2024-06-09 11:40:07,366 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:78]
2024-06-09 11:42:36,344 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:78]
2024-06-09 11:44:45,387 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:78]
2024-06-09 11:46:30,580 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:78]
2024-06-09 11:48:51,156 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:78]
2024-06-09 11:50:22,446 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:79]
2024-06-09 11:51:07,054 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:78]
2024-06-09 11:54:26,468 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:78]
2024-06-09 11:58:37,633 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:79]
